version: "3"

# GitHub Actions output grouping when GITHUB_ACTIONS=true or CI=true
output:
  group:
    begin: "::group::{{.TASK}}"
    end: "::endgroup::"

includes:
  build: ./Taskfile.build.yaml
  test: ./Taskfile.test.yaml
  cli: ./Taskfile.pgconfig.yaml

# Default tasks that delegate to included files
tasks:
  # Build shortcuts
  build:
    desc: Build the postgres-upgrade Docker image
    cmds:
      - task: build:build

  build-all:
    desc: Build all target version images
    cmds:
      - task: build:build-all

  # Test shortcuts
  test:
    desc: Test all PostgreSQL upgrades
    cmds:
      - task: build:build
      - task: cli:build
      - task: test:quick

  test-image:
    desc: Build and test Docker image with integration tests
    cmds:
      - task: test:test-image

  clean:
    desc: Clean up everything
    cmds:
      - task: test:clean

  status:
    desc: Show status of volumes and images
    cmds:
      - task: test:status

  # Development shortcuts
  dev-setup:
    desc: Set up development environment
    cmds:
      - task: build:build
      - task: test:dev-setup

  dev-test-quick:
    desc: Quick development test (14 to 17 upgrade only)
    cmds:
      - task: build:build
      - task: test:dev-test-quick

  cli-build:
    desc: Build and install the postgres-cli to GOBIN
    cmds:
      - task: cli:build

  cli-test:
    desc: Run CLI tests
    cmds:
      - task: cli:test

  cli-ci:
    desc: Run complete CLI CI pipeline
    cmds:
      - task: cli:ci
